# Site settings
title: __Web Dev
baseurl: "/"
url: "https://mochirii.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mel Smith
user_description: STEM graduate with a love of computers and an eagle eye when it comes to spotting errors in code. I've grown to love debugging almost as much as I love cooking and tabletop board games. 
user_title: Web Developer
email: melpcsmith@gmail.com
github_username: mochirii
linkedin_username: melpcsmith


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
